[ghoul]
path = "graphics/spritesheets/ghoul.png"
id = 1

[[ghoul.sprites]] # ID: 0
name = "idle"
area = {x = 0, y = 0, width = 64, height = 64}

[[ghoul.sprites]] # ID: 1
name = "walk_1"
area = {x = 64, y = 0, width = 64, height = 64}

[[ghoul.sprites]] # ID: 2
name = "walk_2"
area = {x = 128, y = 0, width = 64, height = 64}

[[ghoul.sprites]] # ID: 3
name = "hit_stun"
area = {x = 192, y = 0, width = 64, height = 64}

[[ghoul.sprites]] # ID: 4
name = "charge"
area = {x = 256, y = 0, width = 64, height = 64}

[[ghoul.sprites]] # ID: 5
name = "attack_1"
area = {x = 0, y = 64, width = 64, height = 64}

[[ghoul.sprites]] # ID: 6
name = "attack_2"
area = {x = 64, y = 64, width = 64, height = 64}

[[ghoul.sprites]] # ID: 7
name = "death_1"
area = {x = 128, y = 64, width = 64, height = 64}

[[ghoul.sprites]] # ID: 8
name = "death_2"
area = {x = 192, y = 64, width = 64, height = 64}

