[player]
id = 0

[[player.sprites]] # ID: 0
name = "idle_rest"
area = {x = 0, y = 0, width = 64, height = 64}

[[player.sprites]] # ID: 1
name = "idle"
area = {x = 64, y = 0, width = 64, height = 64}

[[player.sprites]] # ID: 2
name = "walk_1"
area = {x = 128, y = 0, width = 64, height = 64}

[[player.sprites]] # ID: 3
name = "walk_2"
area = {x = 192, y = 0, width = 64, height = 64}

[[player.sprites]] # ID: 4
name = "charge"
area = {x = 256, y = 0, width = 64, height = 64}

[[player.sprites]] # ID: 5
name = "light_atk"
area = {x = 0, y = 64, width = 64, height = 64}

[[player.sprites]] # ID: 6
name = "heavy_atk"
area = {x = 64, y = 64, width = 64, height = 64}

[[player.sprites]] # ID: 7
name = "hit_stun"
area = {x = 128, y = 64, width = 64, height = 64}

[[player.sprites]] # ID: 8
name = "guard"
area = {x = 192, y = 64, width = 64, height = 64}

[[player.sprites]] # ID: 9
name = "parry"
area = {x = 256, y = 64, width = 64, height = 64}

[[player.sprites]] # ID: 10
name = "knife_light1"
area = {x = 0, y = 128, width = 64, height = 64}

[[player.sprites]] # ID: 11
name = "knife_light2"
area = {x = 64, y = 128, width = 64, height = 64}

[[player.sprites]] # ID: 12
name = "knife_light3"
area = {x = 128, y = 128, width = 64, height = 64}

[[player.sprites]] # ID: 13
name = "knife_heavy1"
area = {x = 192, y = 128, width = 64, height = 64}

[[player.sprites]] # ID: 14
name = "knife_heavy2"
area = {x = 256, y = 128, width = 64, height = 64}

[[player.sprites]] # ID: 15
name = "death_1"
area = {x = 0, y = 192, width = 64, height = 64}

[[player.sprites]] # ID: 16
name = "death_2"
area = {x = 64, y = 192, width = 64, height = 64}

[[player.sprites]] # ID: 17
name = "endure_1"
area = {x = 128, y = 192, width = 64, height = 64}

[[player.sprites]] # ID: 18
name = "endure_2"
area = {x = 192, y = 192, width = 64, height = 64}
