[player]
path = "graphics/spritesheets/player.png"
id = 0

[[player.sprites]] # ID: 0
name = "idle_rest"
area = {x = 0, y = 0, width = 64, height = 64}

[[player.sprites]] # ID: 1
name = "idle"
area = {x = 64, y = 0, width = 64, height = 64}

[[player.sprites]] # ID: 2
name = "walk_1"
area = {x = 128, y = 0, width = 64, height = 64}

[[player.sprites]] # ID: 3
name = "walk_2"
area = {x = 192, y = 0, width = 64, height = 64}

[[player.sprites]] # ID: 4
name = "charge"
area = {x = 256, y = 0, width = 64, height = 64}

[[player.sprites]] # ID: 5
name = "light_atk"
area = {x = 0, y = 64, width = 64, height = 64}

[[player.sprites]] # ID: 6
name = "heavy_atk"
area = {x = 64, y = 64, width = 64, height = 64}

[[player.sprites]] # ID: 7
name = "hit_stun"
area = {x = 128, y = 64, width = 64, height = 64}

[[player.sprites]] # ID: 8
name = "guard"
area = {x = 192, y = 64, width = 64, height = 64}

[[player.sprites]] # ID: 9
name = "parry"
area = {x = 256, y = 64, width = 64, height = 64}

[[player.sprites]] # ID: 10
name = "knife_light1"
area = {x = 0, y = 128, width = 64, height = 64}

[[player.sprites]] # ID: 11
name = "knife_light2"
area = {x = 64, y = 128, width = 64, height = 64}

[[player.sprites]] # ID: 12
name = "knife_light3"
area = {x = 64, y = 128, width = 64, height = 64}


[ghoul]
path = "graphics/spritesheets/ghoul.png"
id = 1

[[ghoul.sprites]] # ID: 0
name = "idle"
area = {x = 0, y = 0, width = 64, height = 64}

[[ghoul.sprites]] # ID: 1
name = "walk_1"
area = {x = 64, y = 0, width = 64, height = 64}

[[ghoul.sprites]] # ID: 2
name = "walk_2"
area = {x = 128, y = 0, width = 64, height = 64}

[[ghoul.sprites]] # ID: 3
name = "hit_stun"
area = {x = 192, y = 0, width = 64, height = 64}

[[ghoul.sprites]] # ID: 4
name = "charge"
area = {x = 256, y = 0, width = 64, height = 64}

[[ghoul.sprites]] # ID: 5
name = "attack_1"
area = {x = 0, y = 64, width = 64, height = 64}

[[ghoul.sprites]] # ID: 6
name = "attack_2"
area = {x = 64, y = 64, width = 64, height = 64}

[[ghoul.sprites]] # ID: 7
name = "death_1"
area = {x = 128, y = 64, width = 64, height = 64}

[[ghoul.sprites]]
name = "death_2"
area = {x = 192, y = 64, width = 64, height = 64}


[hud_life]
path = "graphics/spritesheets/hud_life.png"
id = 2

[[hud_life.sprites]] # ID: 0
name = "frame"
area = {x = 0, y = 0, width = 80, height = 21}

[[hud_life.sprites]] # ID: 1
name = "gauge"
area = {x = 8, y = 22, width = 69, height = 9}

[[hud_life.sprites]] # ID: 2
name = "empty_white"
area = {x = 8, y = 32, width = 69, height = 9}

[[hud_life.sprites]] # ID: 3
name = "empty_red"
area = {x = 8, y = 42, width = 69, height = 9}

[hud_morale]
path = "graphics/spritesheets/hud_morale.png"
id = 3

[[hud_morale.sprites]] # ID: 0
name = "frame"
area = {x = 0, y = 0, width = 79, height = 17}

[[hud_morale.sprites]] # ID: 1
name = "empty"
area = {x = 7, y = 18, width = 70, height = 6}

[[hud_morale.sprites]] # ID: 2
name = "gauge"
area = {x = 7, y = 25, width = 70, height = 6}
