[player]
path = "graphics/spritesheets/player.png"
sprites = [
  # idle_rest - 0
  {x = 0, y = 0, width = 64, height = 64},
  # idle_action - 1
  {x = 64, y = 0, width = 64, height = 64},
  # walk_1 - 2
  {x = 128, y = 0, width = 64, height = 64},
  # walk_2 - 3
  {x = 192, y = 0, width = 64, height = 64}
]

