[weapon_select]
id = 7

[[weapon_select.sprites]] # ID: 0
name = "select_frame"
area = {x = 0, y = 0, width = 426, height = 56}

[[weapon_select.sprites]] # ID: 1
name = "tech_window"
area = {x = 0, y = 56, width = 234, height = 56}

[[weapon_select.sprites]] # ID: 2
name = "arrow"
area = {x = 240, y = 64, width = 16, height = 8}

[[weapon_select.sprites]] # ID: 3
name = "icon_none"
area = {x = 256, y = 64, width = 16, height = 16}

[[weapon_select.sprites]] # ID: 4
name = "icon_knife"
area = {x = 272, y = 64, width = 16, height = 16}

[[weapon_select.sprites]] # ID: 5
name = "icon_ball"
area = {x = 288, y = 64, width = 16, height = 16}

[[weapon_select.sprites]] # ID: 6
name = "icon_gun"
area = {x = 304, y = 64, width = 16, height = 16}
