# Menu Sound Effects
[[sfx]]
name = "opt_change"
path = "audio/sfx/opt_change.wav"

[[sfx]]
name = "opt_confirm"
path = "audio/sfx/opt_confirm.wav"

[[sfx]]
name = "opt_cancel"
path = "audio/sfx/opt_cancel.wav"

[[sfx]]
name = "opt_error"
path = "audio/sfx/opt_error.wav"

# Gameplay Sound Effects
[[sfx]]
name = "timer_low"
path = "audio/sfx/timer_low.wav"

[[sfx]]
name = "wave_next"
path = "audio/sfx/wave_next.wav"

[[sfx]]
name = "damage" 
path = "audio/sfx/damage.wav"

pitch_random = true
pitch_min = 0.75
pitch_max = 1.25

[[sfx]]
name = "critical_health"
path = "audio/sfx/critical_health.wav"

[[sfx]]
name = "cmd_cancel"
path = "audio/sfx/cmd_cancel.wav"

[[sfx]]
name = "weapon_error"
path = "audio/sfx/weapon_error.wav"

[[sfx]]
name = "weapon_ready"
path = "audio/sfx/weapon_ready.wav"

[[sfx]]
name = "knife_light"
path = "audio/sfx/knife_light.wav"

[[sfx]]
name = "knife_heavy"
path = "audio/sfx/knife_heavy.wav"

[[sfx]]
name = "ball_light_juke"
path = "audio/sfx/ball_light_juke.wav"

[[sfx]]
name = "ball_light_break"
path = "audio/sfx/ball_light_break.wav"

[[sfx]]
name = "ball_heavy_chain"
path = "audio/sfx/ball_heavy_chain.wav"

[[sfx]]
name = "ball_heavy_kick"
path = "audio/sfx/ball_heavy_kick.wav"

[[sfx]]
name = "death"
path = "audio/sfx/death.wav"

[[sfx]]
name = "guard_success"
path = "audio/sfx/guard_success.wav"

[[sfx]]
name = "guard_fail"
path = "audio/sfx/guard_fail.wav"

[[sfx]]
name = "parry"
path = "audio/sfx/parry.wav"

[[sfx]]
name = "gol_warning"
path = "audio/sfx/gol_warning.wav"

[[sfx]]
name = "wrh_warning"
path = "audio/sfx/wrh_warning.wav"

[[sfx]]
name = "wrh_attack"
path = "audio/sfx/wrh_attack.wav"

[[sfx]]
name = "dam_damage_tick"
path = "audio/sfx/dam_damage_tick.wav"

[[sfx]]
name = "dam_alert"
path = "audio/sfx/dam_alert.wav"

[[sfx]]
name = "dam_release"
path = "audio/sfx/dam_release.wav"

[[sfx]]
name = "dam_struggle"
path = "audio/sfx/dam_struggle.wav"

[[sfx]]
name = "dam_struggle_free"
path = "audio/sfx/dam_struggle_free.wav"
